import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css'
import './globals.css'
import { Theme, ThemePanel } from '@radix-ui/themes'
import Navbar from './components/Navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <Theme accentColor='gray'>
          <Navbar />
          {children}
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  )
}
